import { defineConfig } from 'vite-plus'

export default defineConfig({
  defaultPackage: {
    dev: './apps/web',
    build: './apps/web',
    preview: './apps/web',
  },
  staged: {
    '*': 'vp check --fix',
  },
  fmt: {
    semi: false,
    singleQuote: true,
  },
  lint: {
    plugins: ['typescript', 'oxc'],
    jsPlugins: [{ name: 'vite-plus', specifier: 'vite-plus/oxlint-plugin' }],
    rules: { 'vite-plus/prefer-vite-plus-imports': 'error' },
    options: { typeAware: true, typeCheck: true },
    overrides: [
      {
        files: ['apps/web/**'],
        plugins: ['react'],
        rules: {
          'react/rules-of-hooks': 'error',
          'react/only-export-components': ['warn', { allowConstantExport: true }],
        },
      },
      {
        // Generated by shadcn: components export their variant helpers too.
        files: ['apps/web/src/components/ui/**', 'apps/web/src/hooks/**'],
        plugins: ['react'],
        rules: { 'react/only-export-components': 'off', 'react/set-state-in-effect': 'off' },
      },
    ],
  },
  run: {
    cache: true,
    tasks: {
      fixtures: {
        command: 'node scripts/fetch-fixtures.ts',
        cache: false,
      },
    },
  },
})
