/**
 * Generates src/generated/game-data.json from a local Oxygen Not Included install:
 * - English names and descriptions from StreamingAssets/strings/strings_template.pot
 * - exact IDs (e.g. "BingeEater") recovered from string literals in Managed/Assembly-CSharp.dll,
 *   because the strings file only has upper-cased keys (STRINGS.DUPLICANTS.TRAITS.BINGEEATER).
 *
 * Usage: vp run extract-game-data   (set ONI_PATH to the game folder if it isn't the Steam default)
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'

const DEFAULT_PATHS = [
  join(
    homedir(),
    'Library/Application Support/Steam/steamapps/common/OxygenNotIncluded/OxygenNotIncluded.app/Contents/Resources/Data',
  ),
  'C:/Program Files (x86)/Steam/steamapps/common/OxygenNotIncluded/OxygenNotIncluded_Data',
  join(homedir(), '.steam/steam/steamapps/common/OxygenNotIncluded/OxygenNotIncluded_Data'),
]

function dataDir(): string {
  const env = process.env.ONI_PATH
  const candidates = env
    ? [
        env,
        join(env, 'OxygenNotIncluded.app/Contents/Resources/Data'),
        join(env, 'OxygenNotIncluded_Data'),
      ]
    : DEFAULT_PATHS
  const found = candidates.find((p) =>
    existsSync(join(p, 'StreamingAssets/strings/strings_template.pot')),
  )
  if (!found) throw new Error(`Game data not found. Set ONI_PATH. Tried:\n${candidates.join('\n')}`)
  return found
}

/** msgctxt → msgid from a gettext template. */
function readPot(path: string): Map<string, string> {
  const unquote = (s: string) => JSON.parse(s) as string
  const entries = new Map<string, string>()
  let ctxt: string | null = null
  let target: 'ctxt' | 'id' | null = null
  let id = ''
  const flush = () => {
    if (ctxt !== null) entries.set(ctxt, id)
    ctxt = null
    id = ''
  }
  for (const line of readFileSync(path, 'utf8').split('\n')) {
    if (line.startsWith('msgctxt ')) {
      flush()
      ctxt = unquote(line.slice(8))
      target = 'ctxt'
    } else if (line.startsWith('msgid ')) {
      id = unquote(line.slice(6))
      target = 'id'
    } else if (line.startsWith('"') && target === 'id') {
      id += unquote(line)
    } else if (line.startsWith('msgstr')) {
      target = null
    }
  }
  flush()
  return entries
}

/** Upper-cased identifier → identifiers found as UTF-16 string literals in the assembly. */
function readAssemblyLiterals(path: string): Map<string, string[]> {
  const bytes = readFileSync(path)
  const byUpper = new Map<string, string[]>()
  let run = ''
  const flush = () => {
    if (run.length >= 2 && /^[A-Za-z][A-Za-z0-9_]*$/.test(run)) {
      const key = run.toUpperCase()
      const list = byUpper.get(key) ?? []
      if (!list.includes(run)) list.push(run)
      byUpper.set(key, list)
    }
    run = ''
  }
  for (let i = 0; i + 1 < bytes.length; i += 1) {
    const c = bytes[i]!
    if (bytes[i + 1] === 0 && c >= 0x20 && c < 0x7f) {
      run += String.fromCharCode(c)
      i += 1
    } else {
      flush()
    }
  }
  flush()
  return byUpper
}

const clean = (text: string) => text.replace(/<[^>]+>/g, '').trim()

const sdbmLower = (s: string) => {
  let h = 0
  for (const ch of s.toLowerCase()) h = (ch.charCodeAt(0) + (h << 6) + (h << 16) - h) | 0
  return h
}

interface Entry {
  id: string
  name: string
  desc?: string
}

function collect(
  strings: Map<string, string>,
  literals: Map<string, string[]>,
  prefix: string,
  { exactId = false }: { exactId?: boolean } = {},
): Entry[] {
  const entries: Entry[] = []
  const re = new RegExp(`^${prefix.replace(/\./g, '\\.')}([A-Z0-9_]+)\\.NAME$`)
  for (const [key, name] of strings) {
    const match = re.exec(key)
    if (!match) continue
    const upper = match[1]!
    const candidates = literals.get(upper) ?? []
    // Prefer a mixed-case literal (the real ID) over an all-caps constant.
    const id = exactId ? upper : (candidates.find((c) => c !== upper) ?? candidates[0])
    if (!id) continue
    const desc =
      strings.get(`${prefix}${upper}.DESC`) ?? strings.get(`${prefix}${upper}.DESCRIPTION`)
    entries.push({ id, name: clean(name), ...(desc ? { desc: clean(desc) } : {}) })
  }
  return entries.sort((a, b) => a.name.localeCompare(b.name))
}

const dir = dataDir()
const strings = readPot(join(dir, 'StreamingAssets/strings/strings_template.pot'))
const literals = readAssemblyLiterals(join(dir, 'Managed/Assembly-CSharp.dll'))

const data = {
  source:
    "Generated by packages/game-data/scripts/extract-game-data.ts from the game's strings and assembly.",
  traits: collect(strings, literals, 'STRINGS.DUPLICANTS.TRAITS.'),
  attributes: collect(strings, literals, 'STRINGS.DUPLICANTS.ATTRIBUTES.'),
  skillGroups: collect(strings, literals, 'STRINGS.DUPLICANTS.SKILLGROUPS.').map((g) => ({
    ...g,
    hash: sdbmLower(g.id),
  })),
  amounts: collect(strings, literals, 'STRINGS.DUPLICANTS.STATS.'),
  effects: collect(strings, literals, 'STRINGS.DUPLICANTS.MODIFIERS.'),
  personalities: collect(strings, literals, 'STRINGS.DUPLICANTS.PERSONALITIES.', { exactId: true }),
  geysers: collect(strings, literals, 'STRINGS.CREATURES.SPECIES.GEYSER.', { exactId: true }),
}

const out = new URL('../src/generated/game-data.json', import.meta.url)
writeFileSync(out, `${JSON.stringify(data, null, 1)}\n`)
for (const [k, v] of Object.entries(data)) if (Array.isArray(v)) console.log(`${k}: ${v.length}`)
